name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          # This fetches the entire Git history so that Changesets can generate changelogs with the correct commits.
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun run changeset version
          publish: bun run build && bun run tsc && bun run changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
